"use client";
import { FormEvent, useState } from "react";

export default function AuthPage({ mode }: { mode: "login" | "register" }) {
  const [loading, setLoading] = useState(false);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); window.location.href="https://gateway.ijatllm.my.id/ui/login/?source=info"; }
  const register = mode === "register";
  return <main className="auth-shell"><section className="auth-showcase"><a className="brand light-brand" href="/"><img className="brand-logo-image" src="/ijatllm-logo.svg" alt="IjatLLM"/></a><div className="auth-copy"><span className="eyebrow dark"><span className="pulse"/> DEVELOPER-FIRST AI GATEWAY</span><h1>{register?"Mulai membangun dengan AI hari ini.":"Selamat datang kembali."}</h1><p>{register?"Satu akun memberi Anda akses ke model AI terbaik, pembayaran lokal, dan observabilitas lengkap.":"Kelola API key, budget, penggunaan, dan seluruh model AI dari satu dashboard."}</p><div className="auth-benefits"><span><i>âœ“</i><b>Integrasi cepat<small>Kompatibel dengan OpenAI SDK</small></b></span><span><i>âœ“</i><b>Kontrol penuh<small>Budget, rate limit, dan audit log</small></b></span><span><i>âœ“</i><b>Pembayaran rupiah<small>QRIS, VA, dan e-wallet lokal</small></b></span></div></div><div className="auth-quote"><p>â€œSatu akses aman untuk dashboard, wallet, tim, dan seluruh API key.â€</p><span><b>IjatLLM Security</b><small>Identitas dikelola melalui ChatGPT Sign In</small></span></div></section><section className="auth-form-wrap"><div className="auth-mobile-brand"><a className="brand" href="/"><img className="brand-logo-image" src="/ijatllm-logo.svg" alt="IjatLLM"/></a></div><form className="auth-form" onSubmit={submit}><span className="kicker">{register?"BUAT AKUN BARU":"PORTAL PENGGUNA"}</span><h2>{register?"Daftar IjatLLM":"Masuk ke IjatLLM"}</h2><p>{register?"Sudah memiliki akun?":"Belum punya akun?"} <a href={register?"/login":"/register"}>{register?"Masuk di sini":"Daftar gratis"}</a></p>{register&&<><label>Nama workspace<input name="workspace" required minLength={3} placeholder="Contoh: Nusantara Labs"/></label><label className="terms"><input type="checkbox" required/> Saya menyetujui <a href="/terms">Syarat Layanan</a> dan <a href="/privacy">Kebijakan Privasi</a>.</label></>}<button className="action primary-action auth-submit" disabled={loading}>{loading?"Mengalihkan...":register?"Daftar dengan ChatGPT":"Masuk dengan ChatGPT"}<span>â†’</span></button><div className="auth-security"><i>â—†</i><div><b>Login tanpa password IjatLLM</b><p>Identitas diverifikasi oleh ChatGPT. IjatLLM tidak menerima atau menyimpan password Anda.</p></div></div><small className="auth-note">Setelah autentikasi, Anda kembali ke dashboard dan data dipisahkan berdasarkan akun yang terverifikasi.</small></form><a className="back-link" href="/">â† Kembali ke beranda</a></section></main>
}

